### ISSUE TITLE
Preserve open/split windows layout

### ISSUE THREAD

**Issue by machel2** [vim-ctrlspace/vim-ctrlspace#265] opened 2020-04-19 08:25 UTC
**Is your feature request related to a problem? Please describe.**
Workspace doesn't save windows layout in tabs. On load it open only single window per tab, no matter how many windows was displayed (vertical/horizontal split) on save.

I have few tabs where i have always 2-4 windows open at once next to each other. When i load workspace only one of them is displayed.

**Describe the solution you'd like**
Windows layout in each tab should be restored when workspace is loaded

**Describe alternatives you've considered**
Split windows manually on each workspace load

**Additional context**
none

**Version(s) (please complete the following information):**
 - OS: linux
 - Version: nvim v0.4.3

**Comment by Konfekt** [comment] 2020-04-20 07:38
Strange, I can confirm but it was solved in https://github.com/vim-ctrlspace/vim-ctrlspace/issues/56
What caused this regression? Can you confirm it works for you after https://github.com/vim-ctrlspace/vim-ctrlspace/commit/fbd0f05b4d37cc45ef2ede469efb7f5164d30de1 ?

**Comment by amiller27** [comment] 2020-05-01 20:33
I'm seeing this bug as well (ubuntu 20.04, vim-gtk 8.1.2269 and vim-gtk 8.2.0647), git bisect puts it at 88da905.  I have several tab-related commands in the working `.cs_workspaces` that aren't present after that commit, such as `tabnew`, `tabrewind`, and `tabnext 2`, which I think are probably the cause.  Lots of other lines are gone after the commit, but I assume those are intended effects and the tab-related issues are causing the bug.

**Comment by Konfekt** [comment] 2020-05-02 07:22
On first impression, the commit https://github.com/vim-ctrlspace/vim-ctrlspace/commit/88da905e65ee070d3db450b1832ffe171db894a4 seems sensible and discards lines meant to be discarded but previously were note.

Instead perhaps the check https://github.com/vim-ctrlspace/vim-ctrlspace/blob/88da905e65ee070d3db450b1832ffe171db894a4/autoload/ctrlspace/workspaces.vim#L395 throws out commands `tabnew` and `tabedit` meant to be included in Vim newer than 8.1.149?

**Comment by amiller27** [comment] 2020-05-02 16:39
Yes, I agree.  I think the bug fixed in 88da905 was covering up the error, the fix should be modifications to the line you linked, I'm just not familiar enough to know how exactly it should be fixed to work with different vim versions, etc.

**Comment by Konfekt** [comment] 2020-05-02 18:26
If you remove the check 

https://github.com/vim-ctrlspace/vim-ctrlspace/blob/88da905e65ee070d3db450b1832ffe171db894a4/autoload/ctrlspace/workspaces.vim#L396

then do the splits come back?

**Comment by Konfekt** [comment] 2020-05-02 18:47
These checks were supposed to solve https://github.com/vim-ctrlspace/vim-ctrlspace/issues/202 as indicated in https://github.com/vim-ctrlspace/vim-ctrlspace/issues/202#issuecomment-410082543 and committed in https://github.com/vim-ctrlspace/vim-ctrlspace/commit/1a285ba05c2141ec161960af5b693420768b3105

**Comment by amiller27** [comment] 2020-05-02 22:10
Ok, so I'm testing with a simple workspace with 2 tabs, one file each.  Pre-88da905, the .cs_workspaces file contains:
```
CS_LAST_WORKSPACE: test
CS_WORKSPACE_BEGIN: test
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
silent tabonly
exe "cd " . escape(expand("<sfile>:p:h"), ' ')
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
argglobal
%argdel
tabnew
tabrewind
edit bat.py
edit bat.py
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
argglobal
let s:l = 1 - ((0 * winheight(0) + 38) / 76)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
tabnext
edit examples.desktop
edit examples.desktop
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
argglobal
let s:l = 1 - ((0 * winheight(0) + 37) / 75)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
tabnext 2
badd +0 bat.py
badd +1 examples.desktop
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToOSc
set winminheight=1 winminwidth=1
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save
nohlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
CS_WORKSPACE_END: test
```

The current version of CtrlSpace generates this, which opens both buffers in one tab:
```
CS_LAST_WORKSPACE: test
CS_WORKSPACE_BEGIN: test
edit bat.py
edit bat.py
tabnext
edit examples.desktop
badd +0 bat.py
badd +1 examples.desktop
CS_WORKSPACE_END: test
```

Replacing lines 395-396 with one line `\ || ((cmd =~# "^tabnew") || (cmd =~# "^tabedit") || (cmd =~# "^tabnext$"))` gives the following, which puts both buffers in the first tab, with the second tab open but empty:
```
CS_LAST_WORKSPACE: test
CS_WORKSPACE_BEGIN: test
edit bat.py
edit examples.desktop
tabnew
tabnext
badd +1 bat.py
badd +1 examples.desktop
CS_WORKSPACE_END: test
```

And finally, editing the pre-88da905 version down to something which reproduces the correct result (not sure if this is minimal or not) gives:
```
CS_LAST_WORKSPACE: test
CS_WORKSPACE_BEGIN: test
tabnew
tabrewind
edit bat.py
edit bat.py
tabnext
edit examples.desktop
edit examples.desktop
tabnext 2
badd +0 bat.py
badd +1 examples.desktop
CS_WORKSPACE_END: test
```

**Comment by Konfekt** [comment] 2020-05-10 09:35
Please testdrive https://github.com/vim-ctrlspace/vim-ctrlspace/pull/268 and see if it works better with your Vim. My version is lower than `8.1.149`.

**Comment by amiller27** [comment] 2020-05-10 18:43
Yep, that appears to fix the issue (tested on Vim 8.1.2269)

**Comment by Konfekt** [comment] 2020-05-10 19:55
Perhaps @cometsong wants to confirm?

**Comment by alteriks** [comment] 2020-05-23 21:12
@Konfekt Today I've installed vim-ctrlspace and after struggling with configuration in neovim I initially thought that ctrlspace doesn't save layout. 
It's only mentioned here https://github.com/vim-ctrlspace/vim-ctrlspace/blob/master/doc/ctrlspace.txt#L184-L186 I think it should also be stressed in ctrlspace-workspace-list part.

Last but not least I've stumbled upon this issue. I've tried your branch and it works great.

**Comment by Konfekt** [comment] 2020-05-24 08:55
Yes, looking at the function to save a workspace showed it to be just that to save a session plus the buffer lists for each tab (minus the local work dir). In particular, the window layout is preserved. 

https://github.com/vim-ctrlspace/vim-ctrlspace/pull/268 now also mentions that the layout is saved where  indicated.

**Comment by jyscao** [comment] 2020-11-09 23:11
The main issue raised here should now be fixed. See #277

**Closed by jyscao** 2020-11-09 23:11 UTC
