### ISSUE TITLE
Sometimes the current layout window shrinks to max when triggering the buffer list.

### ISSUE THREAD

**Issue by jmolero** [vim-ctrlspace/vim-ctrlspace#271] opened 2020-06-08 14:06 UTC
**Describe the bug**
Sometimes when I fire the buffer list the current layout windows shrink to the maximum showing only the buffer list at the top. It's a bit annoying because then I have to type ```<C-W>_``` to make it full height again.

**To Reproduce**

Seems to happend randomly when firing the buffer list but it's been happening for a while now.

**Expected behavior**
Any ctrlspace list should show without affecting the current layout.

**Version(s) (please complete the following information):**
 - OS: osx catalina
 - Version: NVIM v0.4.3

**Additional context**
At first I thought that it might be another plugin like coc-explorer which I use as a file drawer that caused the problem but it also happens with it closed.

**Comment by jmolero** [comment] 2020-07-17 15:19
Any idea why that happens? Or maybe you can give me a hint on what to look for to try to find the cause?

**Comment by mellery451** [comment] 2020-07-20 15:48
having the same issue here..and I've noticed this issue for approximately the last 12 months. I'm using HEAD of nvim - haven't tested with vim recently.

**Comment by Konfekt** [comment] 2020-07-31 11:35
If you could test with Vim to check whether the issue is due to nvim or this plug-in?

**Comment by toasterbath255** [comment] 2020-10-23 00:51
I can reproduce this issue using Neovim + Coc.

Steps to reproduce
1. Open a file that Coc checks for errors.
2. Type erroneous code.
3. Move your cursor on erroneous code.
4. Make sure floating window containing error message has appeared.
![Screen Capture_select-area_20201023094054](https://user-images.githubusercontent.com/66874440/96943961-8af87500-1514-11eb-988a-8a5119579636.png)
5. Now any action with CtrlSpace interface will cause this issue when the interface is closed.

**Comment by jyscao** [comment] 2020-11-10 04:25
@jmolero does this only happen when used in conjunction with CoC, or does it also occur without?

@mellery451 likewise, I ask you the same.

**Comment by jmolero** [comment] 2020-11-10 15:41
@jyscao Must be that. I was also using Coc with ctrlspace.

**Comment by mellery451** [comment] 2020-11-10 16:39
yeah, I also always have Coc enabled...and I'm able to consistently reproduce using the steps outlined by @toasterbath255 - probably that's the issue. So is this somehow related to the floating window/popup?

**Comment by jyscao** [comment] 2020-11-10 20:27
Personally I use deoplete for completion, but I do intend to switch to a LSP based setup at some point, which will likely be CoC.

So I can help triage and debug this issue then. However I don't want to make any guarantees on the timeline atm.

**Comment by Falkgaard** [comment] 2021-12-27 22:58
CoC and NeoVim user here having the same issue as well.

**Comment by Minion3665** [comment] 2022-09-21 23:10
Looks the same as https://github.com/junegunn/vim-peekaboo/issues/83 (https://github.com/neoclide/coc.nvim/issues/4178)

**Comment by losinggeneration** [comment] 2022-10-27 19:55
It seems that plugins that create windows/buffers can easily trigger this. For example I noticed this in noice and can reproduce the issue 100% of the time with that plugin

https://github.com/folke/noice.nvim/issues/140#issuecomment-1293905344
> It might be that Noice triggers this, since I can create windows/buffers outside of the normal neovim event loop. I could imagine situations where some plugins create windows/buffers, but dont use the buf/win number and instead always use 0. In those cases, they might do calculations on noice win/bufs.

From some quick testing, I can pretty much mitigate the issue completely by not running `ctrlspace#window#GoToStartWindow()` in `ctrlspace#window#Kill`. I'm not sure how appropriate this is as a fix though, because I don't fully understand the internals of how ctrlspace works or how required this function is.

**Comment by Minion3665** [comment] 2022-10-28 05:29
> I'm not sure how appropriate this is as a fix though, because I don't fully understand the internals of how ctrlspace works or how required this function is.
> 
> As an edit, I've [created a branch](https://github.com/vim-ctrlspace/vim-ctrlspace/compare/master...losinggeneration:vim-ctrlspace:allow-resize) to...

CoC + nvim, and I've been running with [this commit](https://github.com/vim-ctrlspace/vim-ctrlspace/commit/c1dfc35a208a86256763cbadb6770636b4720b6f), which comments out the line in `ctrlspace#window#GoToStartWindow()` that resizes the windows, for over a month now.

I've not noticed any issues. It's possible that my workflow just doesn't encourage them, but it's probably at least not very required for everyone.

**Comment by Konfekt** [comment] 2022-10-29 05:14
I'd happily merge that; if only we had a bit better idea on 

> that this probably breaks some esoteric thing somewhere with window resizing, and when I come to that I'll fix it.

**Comment by Minion3665** [comment] 2022-10-29 05:38
> I'd happily merge that; if only we had a bit better idea on
> 
> > that this probably breaks some esoteric thing somewhere with window resizing, and when I come to that I'll fix it.

Absolutely; I'm not sure why this function exists (I'm not familiar with ctrlspace internals) so I'm not sure what it breaks, but I imagine the code is probably there for a reason. I'm not suggesting that it should get merged w/o some more looking into that

**Comment by Konfekt** [comment] 2022-10-29 10:57
I suspect we either drop the `winrestcmd()` calls as the `:help` says that 

```
winrestcmd()	Returns a sequence of |:resize| commands that should restore
		the current window sizes.  Only works properly when no windows
		are opened or closed and the current window and tab page is
		unchanged.
		Example: >
			:let cmd = winrestcmd()
			:call MessWithWindowSizes()
			:exe cmd
```

Therefore either we keep track whether any window was closed or opened in the meanwhile before calling the restore command, or let it be.

So to this end, https://github.com/vim-ctrlspace/vim-ctrlspace/commit/c1dfc35a208a86256763cbadb6770636b4720b6f# looks reasonable to me.

**Comment by Minion3665** [comment] 2022-10-29 11:52
> I suspect we either drop the `winrestcmd()` calls as the `:help` says that
> 
> ```
> winrestcmd()	Returns a sequence of |:resize| commands that should restore
> 		the current window sizes.  Only works properly when no windows
> 		are opened or closed and the current window and tab page is
> 		unchanged.
> 		Example: >
> 			:let cmd = winrestcmd()
> 			:call MessWithWindowSizes()
> 			:exe cmd
> ```
> 
> Therefore either we keep track whether any window was closed or opened in the meanwhile before calling the restore command, or let it be.
> 
> So to this end, [c1dfc35](https://github.com/vim-ctrlspace/vim-ctrlspace/commit/c1dfc35a208a86256763cbadb6770636b4720b6f) looks reasonable to me.

Alright 👍🏼,

in that case I'll tidy it up a bit and make a PR

**Closed** 2022-10-30 13:30 UTC
Labels: priority: 1 - middle, bug: interaction
